version: '2.0'

# networks
# create a network 'cockpit' in mode 'bridged'
networks:
  cockpit:
    driver: bridge
volumes:
  rabbitmq_data:
    driver: local
  init_gpg:
    driver: local
  data_gcg:
    driver: local
  init_cpg:
    driver: local
  data_cpg:
    driver: local
  drive:
    driver: local
  record:
    driver: local

# services
services:
  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      cockpit:
    restart: on-failure
    volumes:
    - 'drive:/drive:rw'
    - 'record:/record:rw'
  # postgres
  guacamole_pg:
    container_name: guacamole_pg
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'dd0aa4251547c12c941cde21'
      POSTGRES_USER: guacamole_user
    image: postgres:13.4
    networks:
      cockpit:
    ports:
    - 8543:5432/tcp
    restart: on-failure
    volumes:
    - 'init_gpg:/docker-entrypoint-initdb.d:ro'
    - 'data_gcg:/var/lib/postgresql/data:rw'

  # guacamole
  guacamole: &guacamole
    container_name: guacamole
    depends_on:
    - guacamole_pg
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: guacamole_pg
      POSTGRES_PASSWORD: 'dd0aa4251547c12c941cde21'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    ports:
      - 8080:8080/tcp  
    links:
    - guacd
    networks:
      cockpit:
    restart: on-failure
  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    networks:
      - cockpit
    volumes:
    - './liquibase:/liquibase/changelog:rw'
    command: /liquibase/liquibase --changeLogFile="guacamole_init.postgres.sql" --classpath=/liquibase/changelog --url="jdbc:postgresql://guacamole_pg:5432/guacamole_db?user=guacamole_user&password=dd0aa4251547c12c941cde21"  --log-level=DEBUG update 
    depends_on:
    - guacamole_pg
    - guacamole
    - guacd

########### optional ################################################
  # nginx
#   nginx:
#    container_name: nginx_guacamole_compose
#    restart: on-failure
#    image: nginx
#    volumes:
#    - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
#    - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
#    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    - ./nginx/mysite.template:/etc/nginx/conf.d/default.conf:ro
#    ports:
#    - 8443:443
#    links:
#    - guacamole
#    networks:
#      cockpit:
#    command: /bin/bash -c "nginx -g 'daemon off;'"
# # nginx-debug-mode
# #   command: /bin/bash -c "nginx-debug -g 'daemon off;'"
#########################################################################

##SSH-server
  openssh-server:
    image: lscr.io/linuxserver/openssh-server
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # - PUBLIC_KEY=yourpublickey #optional
      # - PUBLIC_KEY_FILE=/path/to/file #optional
      # - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      # - PUBLIC_KEY_URL=https://github.com/username.keys #optional
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=password #optional
      # - USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=linuxserver #optional
    networks:
      cockpit:
    ports:
      - 2222:2222
    restart: unless-stopped
  #cockpit platform pg
  platform_pg:
    container_name: platform_pg
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: platform_db
      POSTGRES_PASSWORD: 'e8bfc3e6d12443830116b721'
      POSTGRES_USER: platform_user
    image: postgres:13.4
    networks:
      cockpit:
    ports:
    - 9543:5432/tcp
    restart: on-failure
    volumes:
    - 'init_cpg:/docker-entrypoint-initdb.d:ro'
    - 'data_cpg:/var/lib/postgresql/data:rw'  
  #cockpit_app
  cockpitapp: &cockpitapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: cockpitapp
    command: 
    - /bin/bash
    - -c
    - |
      sleep 5
      python manage.py makemigrations platforms
      python manage.py migrate platforms 
      python manage.py makemigrations user
      python manage.py migrate user 
      python manage.py runserver 0.0.0.0:8000
    env_file:
     .envCockpit
    depends_on:
      - guacamole_pg
      - platform_pg
      - guacamole
      - liquibase
    networks:
      - cockpit
  cockpit_celery_worker:
    <<: *cockpitapp
    command: celery -A cockpit worker --loglevel=info --autoscale 4,2
    restart: on-failure
    image: cocktip_celery_worker
    container_name: cockpit_celery_worker    
    networks:
        - cockpit
    ports: []
    depends_on:
      - rabbitmq
      - guacamole
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
    networks:
      - cockpit



