# Generated by Django 4.0.3 on 2022-04-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('public_ip', models.CharField(blank=True, max_length=255)),
                ('private_ip', models.CharField(max_length=255)),
                ('instance_state', models.CharField(choices=[('P', 'PENDING'), ('R', 'RUNNING'), ('S', 'STOPPED'), ('T', 'TERMINATED')], default='PENDING', max_length=255)),
                ('platforms', models.CharField(blank=True, max_length=255)),
                ('platforms_state', models.IntegerField(blank=True)),
            ],
        ),
    ]
