# Generated by Django 4.0.3 on 2022-08-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArgocdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer_token', models.TextField(blank=True, default='None', null=True)),
                ('git_url', models.TextField(blank=True, default='None', null=True)),
                ('username', models.CharField(blank=True, default='None', max_length=255)),
                ('password', models.CharField(blank=True, default='None', max_length=255)),
                ('api_server_endpoint', models.TextField(blank=True, default='None', null=True)),
                ('cluster_name', models.CharField(blank=True, default='None', max_length=255)),
            ],
            options={
                'db_table': 'argocd_config',
            },
        ),
    ]
