# Default values for chart1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.pkg.github.com/knoldus/cockpit-backend/cocktip_celery_guacamole_worker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

imagePullSecrets: 
 - name: github









