PALTFORM_STATUS={
    #1000 SERIES IS MAPPED JENKINS PLATFORM
    #KEYS are INT and VALUES are Message String 
    1000:"JENKINS PLATFORM REQUEST ACCEPETED",
    1001:"JENKINS PLATFROM REQUEST IN_PROGRES",
    1002:"JENKINS PLATFROM REQUEST COMPLETED",
    1003:"JENKINS PLATFROM REQUEST ERORR",
    #2000 SERIES IS MAPPED KUBERNETES PLATFORM
    2000:"KUBERNETES PLATFROM REQUEST ACCEPETED",
    2001:"KUBERNETES PLATFROM REQUEST IN_PROGRES",
    2002:"KUBERNETES PLATFROM REQUEST COMPLETED",
    2003:"KUBERNETES PLATFROM REQUEST ERORR",
    
}
