apiVersion: apps/v1
kind: Deployment
metadata:
  name: cg-deployment
  labels:
    app: cg
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cg
  template:
    metadata:
      labels:
        app: cg
    spec:
      containers:
      - name: cg
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      imagePullSecrets: 
       - name: github
