version: '3.8'
services:
    jenkins:
        depends_on:
        - nginx 
        image: jenkins/jenkins:lts
        container_name: jenkins
        volumes:
            - ./jenkins_home:/var/lib/jenkins/
        ports:
            - '8080:8080'
            - '2000:2000'
        networks:
            - jenkins-net
        restart: unless-stopped
        environment:
            - JENKINS_SLAVE_AGENT_PORT=2000
            - JENKINS_JAVA_OPTIONS=-Djava.awt.headless=true
            - JENKINS_LOG=/var/jenkins_home/logs/jenkins.log
        #command: --enable-future-java
    nginx:
        image: nginx:latest
        volumes:
            - ./data/nginx.conf:/etc/nginx/nginx.conf
            - ./data/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
              #   - ./data/script.sh:/etc/nginx/script.sh
        ports:
            - "80:80"
            - "443:443"
        networks:
            - jenkins-net
        restart: always
networks:
    jenkins-net:
